{
 "title": "Daily Overview",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Current Power Production",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT (-1 * p_3phsum_kw) AS `Net Generation` FROM solar.consumption_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.consumption_meters_data)"
    },
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT p_3phsum_kw AS Production FROM solar.production_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.production_meters_data)"
    },
    {
     "expression": "-1 * ($Power_Production - $Net_Generation)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Energy Generation and Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT \n  CONVERT_TZ(  \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n          ),\n          INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        INTERVAL HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) HOUR\n      ), \n      INTERVAL IF(\n        MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        0,\n        1\n      ) HOUR\n    ),\n    'America/Los_Angeles', 'UTC'\n  ) AS End_Time,\n\tSUM( Nrg_Production ) AS `Energy Production`,\n\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Energy Useage`,\n\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Energy Generation`\nFROM (\n\tSELECT \n\t\tprod.timestamp AS data_time,\n\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\tFROM (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.production_meters_data\n\t\tWHERE data_time >= \n      CONVERT_TZ(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          INTERVAL DAY( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        'America/Los_Angeles', 'UTC' \n      )\n\t) AS prod\n\tJOIN (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.consumption_meters_data\n\t) AS cons\n\tON prod.timestamp = cons.timestamp\n) AS prod_cons\nGROUP BY End_Time\nORDER BY End_Time;"
    }
   ]
  },
  {
   "title": "Today's Energy Generation and Useage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT \n  CONVERT_TZ(  \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n          ),\n          INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        INTERVAL HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) HOUR\n      ), \n      INTERVAL IF(\n        MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        0,\n        1\n      ) HOUR\n    ),\n    'America/Los_Angeles', 'UTC'\n  ) AS End_Time,\n\tSUM( Nrg_Production ) AS `Energy Production`,\n\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Energy Useage`,\n\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Energy Generation`\nFROM (\n\tSELECT \n\t\tprod.timestamp AS data_time,\n\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\tFROM (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.production_meters_data\n\t\tWHERE data_time >= \n      CONVERT_TZ(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          INTERVAL DAY( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        'America/Los_Angeles', 'UTC' \n      )\n\t) AS prod\n\tJOIN (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.consumption_meters_data\n\t) AS cons\n\tON prod.timestamp = cons.timestamp\n) AS prod_cons\nGROUP BY End_Time\nORDER BY End_Time;"
    }
   ]
  },
  {
   "title": "Current Power Production",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT (-1 * p_3phsum_kw) AS `Net Generation` FROM solar.consumption_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.consumption_meters_data)"
    },
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT p_3phsum_kw AS Production FROM solar.production_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.production_meters_data)"
    },
    {
     "expression": "-1 * ($Power_Production - $Net_Generation)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Energy Generation and Useage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT \n  DATE_ADD(\n    DATE_ADD(\n      DATE_ADD(\n        MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n        INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n      ),\n      INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n    ), \n    INTERVAL IF(\n      HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n        MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n      -1,\n      0\n    ) DAY\n  ) AS End_Time,\n\tSUM( Nrg_Production ) AS `Production`,\n\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\nFROM (\n\tSELECT \n\t\tprod.timestamp AS data_time,\n\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\tFROM (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.production_meters_data\n\t\tWHERE data_time >= \n      CONVERT_TZ(\n        DATE_ADD(\n          MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n          INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n        ),\n        'America/Los_Angeles', 'UTC' \n      )\n\t) AS prod\n\tJOIN (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.consumption_meters_data\n\t) AS cons\n\tON prod.timestamp = cons.timestamp\n) AS prod_cons\nGROUP BY End_Time\nORDER BY End_Time;"
    }
   ]
  },
  {
   "title": "Energy Generation and Useage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT \n  DATE_ADD(\n    DATE_ADD(\n      MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n      INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n    ),  \n    INTERVAL IF(\n      DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n      HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n        MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n      -1,\n      0\n    ) MONTH\n  ) AS End_Time,\n\tSUM( Nrg_Production ) AS `Production`,\n\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\nFROM (\n\tSELECT \n\t\tprod.timestamp AS data_time,\n\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\tFROM (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.production_meters_data\n\t\tWHERE data_time >= \n      CONVERT_TZ(\n        MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n        'America/Los_Angeles', 'UTC' \n      )\n\t) AS prod\n\tJOIN (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.consumption_meters_data\n\t) AS cons\n\tON prod.timestamp = cons.timestamp\n) AS prod_cons\nGROUP BY End_Time\nORDER BY End_Time;"
    }
   ]
  },
  {
   "title": "Untransmitted Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT dl_untransmitted AS \"Untransmitted Data\", data_time FROM solar.supervisors_data"
    }
   ]
  }
 ]
}