{
 "title": "Daily Overview",
 "tags": [ "Solar" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM(w.`Production`) AS Production,\n  SUM(w.`Useage`) AS `Usage`,\n  SUM(w.`Net Generation`) AS `Net Generation`\nFROM (\n  SELECT \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n          INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n        ),\n        INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n      ), \n      INTERVAL IF(\n        HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n          MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        -1,\n        0\n      ) DAY\n    ) AS End_Time,\n    SUM( Nrg_Production ) AS `Production`,\n    ( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n    ( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\n  FROM (\n    SELECT \n      prod.timestamp AS data_time,\n      COALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n      COALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n    FROM (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.production_meters_data\n      WHERE data_time >= \n        CONVERT_TZ(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          'America/Los_Angeles', 'UTC' \n        )\n    ) AS prod\n    JOIN (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.consumption_meters_data\n    ) AS cons\n    ON prod.timestamp = cons.timestamp\n  ) AS prod_cons\n  GROUP BY End_Time\n  ORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "title": "Energy Generation and Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM( w.`Net Energy Generation`) OVER ( ORDER BY w.End_Time) AS `Cummulative Net Energy Generation`,\n  w.End_Time AS `End Time`,\n  w.`Energy Production`,\n  w.`Energy Useage`,\n  w.`Net Energy Generation`\nFROM (\n  SELECT \n    CONVERT_TZ(  \n      DATE_ADD(\n        DATE_ADD(\n          DATE_ADD(\n            DATE_ADD(\n              MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n              INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n            ),\n            INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n          ),\n          INTERVAL HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) HOUR\n        ), \n        INTERVAL IF(\n          MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n          0,\n          1\n        ) HOUR\n      ),\n      'America/Los_Angeles', 'UTC'\n    ) AS End_Time,\n    SUM( Nrg_Production ) AS `Energy Production`,\n    ( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Energy Useage`,\n    ( -1 * SUM( Nrg_Consumption ) ) AS `Net Energy Generation`\n  FROM (\n    SELECT \n      prod.timestamp AS data_time,\n      COALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n      COALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n    FROM (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.production_meters_data\n      WHERE data_time >= \n        CONVERT_TZ(\n          DATE_ADD(\n            DATE_ADD(\n              MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n              INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n            ),\n            INTERVAL DAY( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n          ),\n          'America/Los_Angeles', 'UTC' \n        )\n    ) AS prod\n    JOIN (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.consumption_meters_data\n    ) AS cons\n    ON prod.timestamp = cons.timestamp\n  ) AS prod_cons\n  GROUP BY End_Time\n  ORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "title": "Today's Energy Generation and Useage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT \n  CONVERT_TZ(  \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n          ),\n          INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        INTERVAL HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) HOUR\n      ), \n      INTERVAL IF(\n        MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        0,\n        1\n      ) HOUR\n    ),\n    'America/Los_Angeles', 'UTC'\n  ) AS End_Time,\n\tSUM( Nrg_Production ) AS `Energy Production`,\n\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Energy Useage`,\n\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Energy Generation`\nFROM (\n\tSELECT \n\t\tprod.timestamp AS data_time,\n\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\tFROM (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.production_meters_data\n\t\tWHERE data_time >= \n      CONVERT_TZ(\n        DATE_ADD(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          INTERVAL DAY( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n        ),\n        'America/Los_Angeles', 'UTC' \n      )\n\t) AS prod\n\tJOIN (\n\t\tSELECT \n\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\tnet_ltea_3phsum_kwh\n\t\tFROM solar.consumption_meters_data\n\t) AS cons\n\tON prod.timestamp = cons.timestamp\n) AS prod_cons\nGROUP BY End_Time\nORDER BY End_Time;"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM(w.`Energy Production`) AS Production,\n  SUM(w.`Energy Useage`) AS `Usage`,\n  SUM(w.`Net Energy Generation`) AS `Net Generation`\nFROM (\n  SELECT \n    CONVERT_TZ(  \n      DATE_ADD(\n        DATE_ADD(\n          DATE_ADD(\n            DATE_ADD(\n              MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n              INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n            ),\n            INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n          ),\n          INTERVAL HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) HOUR\n        ), \n        INTERVAL IF(\n          MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n          0,\n          1\n        ) HOUR\n      ),\n      'America/Los_Angeles', 'UTC'\n    ) AS End_Time,\n    SUM( Nrg_Production ) AS `Energy Production`,\n    ( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Energy Useage`,\n    ( -1 * SUM( Nrg_Consumption ) ) AS `Net Energy Generation`\n  FROM (\n    SELECT \n      prod.timestamp AS data_time,\n      COALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n      COALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n    FROM (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.production_meters_data\n      WHERE data_time >= \n        CONVERT_TZ(\n          DATE_ADD(\n            DATE_ADD(\n              MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n              INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n            ),\n            INTERVAL DAY( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n          ),\n          'America/Los_Angeles', 'UTC' \n        )\n    ) AS prod\n    JOIN (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.consumption_meters_data\n    ) AS cons\n    ON prod.timestamp = cons.timestamp\n  ) AS prod_cons\n  GROUP BY End_Time\n  ORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM(w.`Production`) AS `Production`,\n  SUM(w.`Useage`) AS `Usage`,\n  SUM(w.`Net Generation`) AS `Net Generation`\nFROM (\n  SELECT \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n          INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n        ),\n        INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n      ), \n      INTERVAL IF(\n        HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n          MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        -1,\n        0\n      ) DAY\n    ) AS End_Time,\n    SUM( Nrg_Production ) AS `Production`,\n    ( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n    ( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\n  FROM (\n    SELECT \n      prod.timestamp AS data_time,\n      COALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n      COALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n    FROM (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.production_meters_data\n      WHERE data_time >= \n        CONVERT_TZ(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          'America/Los_Angeles', 'UTC' \n        )\n    ) AS prod\n    JOIN (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.consumption_meters_data\n    ) AS cons\n    ON prod.timestamp = cons.timestamp\n  ) AS prod_cons\n  GROUP BY End_Time\n  ORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "title": "Energy Generation and Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM( w.`Net Generation`) OVER ( ORDER BY w.End_Time) AS `Cumm. Net Generation`,\n  w.End_Time AS `End Time`,\n  w.`Production`,\n  w.`Useage`,\n  w.`Net Generation`\nFROM (\n  SELECT \n    DATE_ADD(\n      DATE_ADD(\n        DATE_ADD(\n          MAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n          INTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n        ),\n        INTERVAL DAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 DAY\n      ), \n      INTERVAL IF(\n        HOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n          MINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n        -1,\n        0\n      ) DAY\n    ) AS End_Time,\n    SUM( Nrg_Production ) AS `Production`,\n    ( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n    ( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\n  FROM (\n    SELECT \n      prod.timestamp AS data_time,\n      COALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n      COALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n    FROM (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.production_meters_data\n      WHERE data_time >= \n        CONVERT_TZ(\n          DATE_ADD(\n            MAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n            INTERVAL MONTH( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ) -1 MONTH \n          ),\n          'America/Los_Angeles', 'UTC' \n        )\n    ) AS prod\n    JOIN (\n      SELECT \n        FROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n        net_ltea_3phsum_kwh\n      FROM solar.consumption_meters_data\n    ) AS cons\n    ON prod.timestamp = cons.timestamp\n  ) AS prod_cons\n  GROUP BY End_Time\n  ORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "title": "Energy Generation and Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM( w.`Net Generation`) OVER ( ORDER BY w.End_Time) AS `Cumm. Net Generation`,\n  w.End_Time AS `End Time`,\n  w.`Production`,\n  w.`Useage`,\n  w.`Net Generation`\nFROM (\n\tSELECT \n\t\tDATE_ADD(\n\t\t\tDATE_ADD(\n\t\t\t\tMAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n\t\t\t\tINTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n\t\t\t),  \n\t\t\tINTERVAL IF(\n\t\t\t\tDAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n\t\t\t\tHOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n\t\t\t\t\tMINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n\t\t\t\t-1,\n\t\t\t\t0\n\t\t\t) MONTH\n\t\t) AS End_Time,\n\t\tSUM( Nrg_Production ) AS `Production`,\n\t\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n\t\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\n\tFROM (\n\t\tSELECT \n\t\t\tprod.timestamp AS data_time,\n\t\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\t\tFROM (\n\t\t\tSELECT \n\t\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\t\tnet_ltea_3phsum_kwh\n\t\t\tFROM solar.production_meters_data\n\t\t\tWHERE data_time >= \n\t\t\t\tCONVERT_TZ(\n\t\t\t\t\tMAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n\t\t\t\t\t'America/Los_Angeles', 'UTC' \n\t\t\t\t)\n\t\t) AS prod\n\t\tJOIN (\n\t\t\tSELECT \n\t\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\t\tnet_ltea_3phsum_kwh\n\t\t\tFROM solar.consumption_meters_data\n\t\t) AS cons\n\t\tON prod.timestamp = cons.timestamp\n\t) AS prod_cons\n\tGROUP BY End_Time\n\tORDER BY End_Time\n) AS w;"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT\n  SUM(w.`Production`) AS Production,\n  SUM(w.`Useage`) AS `Usage`,\n  SUM(w.`Net Generation`) AS `Net Generation`\nFROM (\n\tSELECT \n\t\tDATE_ADD(\n\t\t\tDATE_ADD(\n\t\t\t\tMAKEDATE(YEAR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ), 1),\n\t\t\t\tINTERVAL MONTH( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) -1 MONTH\n\t\t\t),  \n\t\t\tINTERVAL IF(\n\t\t\t\tDAY( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n\t\t\t\tHOUR( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0 AND\n\t\t\t\t\tMINUTE( CONVERT_TZ( data_time, 'UTC', 'America/Los_Angeles' ) ) = 0,\n\t\t\t\t-1,\n\t\t\t\t0\n\t\t\t) MONTH\n\t\t) AS End_Time,\n\t\tSUM( Nrg_Production ) AS `Production`,\n\t\t( -1 * (SUM( Nrg_Production ) + SUM( Nrg_Consumption ) ) ) AS `Useage`,\n\t\t( -1 * SUM( Nrg_Consumption ) ) AS `Net Generation`\n\tFROM (\n\t\tSELECT \n\t\t\tprod.timestamp AS data_time,\n\t\t\tCOALESCE( prod.net_ltea_3phsum_kwh - LAG( prod.net_ltea_3phsum_kwh ) OVER ( ORDER BY prod.timestamp ASC ), 0 ) AS Nrg_Production,\n\t\t\tCOALESCE( cons.net_ltea_3phsum_kwh - LAG( cons.net_ltea_3phsum_kwh ) OVER ( ORDER BY cons.timestamp ASC ), 0 ) AS Nrg_Consumption\n\t\tFROM (\n\t\t\tSELECT \n\t\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\t\tnet_ltea_3phsum_kwh\n\t\t\tFROM solar.production_meters_data\n\t\t\tWHERE data_time >= \n\t\t\t\tCONVERT_TZ(\n\t\t\t\t\tMAKEDATE(YEAR ( CONVERT_TZ( NOW(), 'UTC', 'America/Los_Angeles' ) ), 1),\n\t\t\t\t\t'America/Los_Angeles', 'UTC' \n\t\t\t\t)\n\t\t) AS prod\n\t\tJOIN (\n\t\t\tSELECT \n\t\t\t\tFROM_UNIXTIME( ( ROUND( UNIX_TIMESTAMP( data_time ) / 60, 0 ) * 60 ) ) AS 'timestamp',\n\t\t\t\tnet_ltea_3phsum_kwh\n\t\t\tFROM solar.consumption_meters_data\n\t\t) AS cons\n\t\tON prod.timestamp = cons.timestamp\n\t) AS prod_cons\n\tGROUP BY End_Time\n\tORDER BY End_Time\n) AS w;\n"
    }
   ]
  },
  {
   "title": "Untransmitted Data",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 3, "y": 14 },
   "targets": [
    {
     "dataset": "solar",
     "rawSql": "SELECT dl_untransmitted AS \"Untransmitted Data\", data_time FROM solar.supervisors_data"
    }
   ]
  },
  {
   "title": "Current Power Production",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kW" } },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT (-1 * p_3phsum_kw) AS `Net Generation` FROM solar.consumption_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.consumption_meters_data)"
    },
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT p_3phsum_kw AS Production FROM solar.production_meters_data WHERE data_time = (SELECT MAX(data_time) FROM solar.production_meters_data)"
    },
    {
     "expression": "-1 * ($Power_Production - $Net_Generation)",
     "type": "math"
    }
   ]
  }
 ]
}